# travis config file for final project, phase 1 (project3)
# http://docs.travis-ci.com/user/build-configuration/

sudo: required

language: python

python:
    - "3.4"

before_install:
    - sudo apt-get update

install:
    - pip install --upgrade pip
    - pip install coverage
    - sudo apt-get install python-numpy
    - pip install Flask
    - pip install requests
    - sudo apt-get install php5-curl

before_script:
    - uname -a
    - printenv
    - pip3 --version
    - pip3 freeze
    - python3 --version
    - coverage3 --version
    - python3 -c "import numpy; print(numpy.__version__)"

script:
    - date
    - git clone https://github.com/cameronreese/no_punt_intended.git
    - ls -al
    - touch IDB.log
    - ls -al
    - make models.html
    - ls -al
    - make -B test
    - cat RunTests.out
    - ls -al
    - make check
