FORMAT: 1A
HOST: http://cfdb.me/punt

# punt

Punt is an api that allows someone to pull meta data about college football players, teams, and conferences

# Punt API Root [/]

This resource does not have any attributes at the root level. Further URL agurgments are required.


## Retrieve the Entry Point [GET]

+ Response 200 (punt/)

        {
            "cfdb.me/punt": "/"
        }

## Group Player

Resources related to the players in the API

## Players [/players/{player_name}]

A Player object has the following attributes:

+ name
+ no [number]
+ pos [position]
+ team [team they play on]
+ ht [height]
+ wt [weight]
+ hometown

+ Parameters
    + player_name: Nick%20Jordan (required, string) - name of the player in the form of a string, spaces substituted with "%20"

### View a Player's Meta Data [GET]

+ Response 200 (punt/players/Nick%20Jordan)

        {
            'name': 'Nick Jordan',
            'no': '#28',
            'pos': 'PK',
            'team': 'Texas Longhorns',
            'ht': '6-1',
            'wt': '193',
            'hometown': 'Coppell, TX',
        }





